### PR TITLE
Add grouping to dotenv

### PR DESCRIPTION
**Pull request by delijati**
This adds the ability to group your env variables by separator:

`.env`
```
a=b
b_a=b
b_d=c
c_b=b
```
result
```
result = dotenv.dotenv_values(dotenv_file, group_sep="_")
print(result)
{'a': 'b', 'b': {'a': 'b', 'd': 'c'}, 'c': {'b': 'b'}}
```
I did it only for one `level` as it would be more confusing than helpful.

### CODE REVIEW

**Comment by theskumar** [comment]
What is the core value that it adds to the project overall? 

Also, I'm interested to know more about the use cases for this format in the context of 12-factor way of managing configuration where the emphasis is to have a simpler config so it's adaptable and not really dependent on the tools used. 

Right now, it feels like this adds more complexity to the codebase and exposes inconsistent APIs of this library.

**Comment by bbc2** [comment]
I agree with @theskumar here.

I would add that if we were to introduce a feature like this in the future, it would most likely be via a new module which would post-process the environment dictionary. That's the same idea as for the type conversion proposal we've received in the past: the env dictionary (`os.environ` or `dotenv_values(...)`) can be processed in a separate step, independently from `load_dotenv` and `dotenv_values`.

For now, I'm not sure such a module would be worth maintaining in python-dotenv. We'd probably need to understand the use case better.

**Comment by delijati** [comment]
Hi sorry for the late response... The use case was `pydantic` and its capability of having nested settings [1]. As you can see in  [2] It is pretty ugly to add a dict to a `.env` file.

To sum it up i ended up using yaml file and not using `BaseSettings` at all [3].

[1] https://github.com/samuelcolvin/pydantic/pull/891

[2] Pydantic can read this e.g. `.env`:
```
foo=2
bla={"ham": 2, "woo": "nice"}
```

Pydantic model:
```
class Extra(BaseModel):
    ham: int
    woo: str

class Settings(BaseSettings):
    foo: int
    bla: Extra
```

[3] load yaml:
```
def load_settings(path):
    with open(path, "r") as ymlfile:
        cfg = yaml.load(ymlfile, Loader=yaml.FullLoader)
        obj = Settings.parse_obj(cfg)
        return obj
```

**Comment by kethan1** [comment]
If you need more advanced config storage, using a json or yaml would be a better idea.

**Comment by theskumar** [comment]
I don't think the new feature like this is justified to be added to this package, and probably need a major effort and planning to implement a new config parser. I'm pretty sure there are other libraries that does this job better already.

**Pull request closed without merging**
