### PR TITLE
Adding option to remove (or not) quotes from values when parsing file

### PR DESCRIPTION
**Pull request by esaporski**
Added flag `remove_quotes` for allowing the parser to remove, or not, quotation marks from the value. `remove_quotes=True` is the default behavior, so this change shouldn't break anything.

This is the return when you run `dotenv.dotenv_values(dotenv_path=file_path)` or `dotenv.dotenv_values(dotenv_path=file_path, remove_quotes=True)`:
```
{
    'MY_VAR': 'testing with quotation marks!',
    'ANOTHER_VAR': 'without quotation marks'
}
```

And with `dotenv.dotenv_values(dotenv_path=file_path, remove_quotes=False)`:
```
{
    'MY_VAR': '"testing with quotation marks!"',
    'ANOTHER_VAR': 'without quotation marks'
}
```

Thanks!

### CODE REVIEW

**Comment by esaporski** [comment]
Just found out that there was an issue open for that #218

**Comment by bbc2** [comment]
Thank you for submitting this pull request. Unfortunately, I'm confused about the problem that it's supposed to solve. If I write `a='"b"'` in a `.env` file, I get `{'a': '"b"'}` from `dotenv_values`, so what's the problem? Quotes are not supposed to be removed by `dotenv_values` if they aren't used as quotes (like the `"` in my example).

**Comment by esaporski** [comment]
Thanks for replying!
The problem is that I need to preserve the quotes inside the variable's value.

For example:
**example.env**
```
DB_NAME=my_database
DB_USER=user42
DB_PW="p4ssw0rd"
DB_ROOT_PW=r00tpasswd
```
Some of the developers I work with are expecting the quotes `"` on that `DB_PW="p4ssw0rd"` variable. They will get the literal value `"p4ssw0rd"`(with the quotes) and parse it inside their application using their prefered programming language (PHP, Javascript, Python, etc).

We are removing the `.env` files from our Github repositories to store them on AWS Secrets Manager. So I need the script to **not** remove the quotes inside the variable's value.

This is what I get when I run the script now:
```python
>>> import dotenv
>>> example = dotenv.dotenv_values(dotenv_path="./example.env")
>>> print(example)
{'DB_NAME': 'my_database', 'DB_USER': 'user42', 'DB_PW': 'p4ssw0rd', 'DB_ROOT_PW': 'r00tpasswd'}
```

This is the behaviour I need:
```python
>>> import dotenv
>>> example = dotenv.dotenv_values(dotenv_path="./example.env", remove_quotes=False)
>>> print(example)
{'DB_NAME': 'my_database', 'DB_USER': 'user42', 'DB_PW': '"p4ssw0rd"', 'DB_ROOT_PW': 'r00tpasswd'}
```

Adding `remove_quotes=False` to the parameters list would return `'DB_PW'` with the value `'"p4ssw0rd"'`.

Again, thanks for taking the time to reply :)

**Comment by bbc2** [comment]
Sorry for the delay, I think I understand now.

It indeed looks like python-dotenv can't solve your issue at the moment.  Unfortunately, I don't think it would be a good idea to support yet another source format in python-dotenv so I'm not willing to merge this, at least for now.

For you migration issue, since your data format looks like it's quite simple, I would suggest a script like the following:

```python
values = {}

with open("env_file") as env_file:
    for line in env_file.readlines():
        (name, value) = line.rstrip("\n").split("=", 1)
        values[name] = value
```

**Comment by bbc2** [comment]
I'm closing this since it's not going to be merged.

**Pull request closed without merging**
