### PR TITLE
[WIP] Add env-containing-directory interpolation

### PR DESCRIPTION
**Pull request by altendky**
#133

### CODE REVIEW

**Comment by altendky** [comment]
py3 passed: https://travis-ci.org/theskumar/python-dotenv/builds/428860919

**Comment by altendky** [comment]
Passed: https://travis-ci.org/theskumar/python-dotenv/builds/428862496

**Comment by dconathan** [comment]
👍 to this feature.  Really would help for setting the `PYTHONPATH`

**Comment by altendky** [comment]
@theskumar any opinions on this?

https://stackoverflow.com/a/2821183/228539

So maybe `=` would be a good prefix to denote variables to be resolved by python-dotenv?  Or do we want them overrideable by previously-existing env vars?

**Comment by altendky** [comment]
@jamesmyatt you could manually create the variable when working with a library lacking such support.  The variable name could have a default but be specifiable.  Or default to `None` for no such functionality.

I thought I shared my in-application workaround but I guess not.  For the record...

https://github.com/altendky/pyqt5-tools/blob/a141af6ed0a325c9326a82bf745cf71151c3c417/src/pyqt5_tools/entrypoints.py#L30-L34
```python
def load_dotenv():
    env_path = dotenv.find_dotenv()
    if len(env_path) > 0:
        os.environ['DOT_ENV_DIRECTORY'] = str(pathlib.Path(env_path).parent)
        dotenv.load_dotenv(dotenv_path=env_path, override=True)
```

Sure, my program could work fine if I specified an absolute path in an environment variable instead of specifying an absolute path in the dot env file using something similar to this PR.  I dunno, "your program should work fine even if this library doesn't end up doing anything" doesn't seem like a great way to guide development.

**Comment by jamesmyatt** [comment]
@altendky, what if there is no dotenv file? what if DOT_ENV_DIRECTORY already exists as an environment variable?

If you need to programmatically determine the base directory of your project, it's far safer to use another file. In R, a standard approach is implemented by the here library: See https://github.com/jennybc/here_here. It's a bad idea to start inventing new things, especially when they won't always work.

**Comment by altendky** [comment]
@jamesmyatt I already addressed those concerns.  Configurable variable name, feature is off by default, and "the config doesn't existing" isn't unique to dot env files and doesn't relate to having features for when the config does exist.  If 'sometimes a file is not there' justifies not handling it when it does...  why does this library exist at all?

Anyways, I'm not trying to find my project root, I'm trying to specify a path _within_ a dot env file which is relative to _that file_.  If a dot env didn't exist...  I wouldn't be trying to specify a path relative to it, so that scenario is unrelated to this feature.  If I wanted to find my project root I would define my project root somehow and find it.  So, that scenario is unrelated.  If we always wrote libraries to the minimal common feature set they would never come into existence, so that's unrelated.

I understand that you dislike this idea in any form but it is unclear to me how it is detrimental to anything.  The default could be for this to be disabled.  When explicitly enabled it doesn't conflict with anything else from what I have thought of.  You can still specify absolute or relative paths (on Linux, you of course get the full four path type options on Windows).  You can still reference any other environment variable.  I just fail to see how this harms any existing functionality or how this feature is different than any other in this library when the dot env file doesn't exist.

**Comment by bbc2** [comment]
Thank you for your efforts but we won't be accepting that feature, at least for now.

**Pull request closed without merging**
