### PR TITLE
WIP: Added support for calling arbitrary script with .env variables provided

### PR DESCRIPTION
**Pull request by venthur**
Hi,

I've started working on a feature that'll allow to use the CLI like this:

```bash
$ dotenv foo
```
which will parse the `.env` file and calls `foo` in a subprocess with the environment variables from `.env` merged with the ones from `os.environ`. This is similar to the behavior of [ruby-dotenv](https://github.com/bkeepers/dotenv).

For now everything is in `dotenv/__main__` so you could easily add another `console_script` in `setup.py`. I've stopped here as I think it would probably better to merge it in the existing `dotenv` script, however I think the **default** action should be as described above, and the existing options from the `dotenv` script should be optional. Please let me know what you think and if and how to proceed.

### CODE REVIEW

**Comment by theskumar** [comment]
Thanks, for making this feature move.

As for the integration, I would prefer to merge this to existing cli. This could be yet another command for running commands.

As for the API, it make sense to have it as:

```
dotenv run <path-to-executable> [-f <path-of-dotenv>]
```

This way it doesn't try to overwrite/conflict any existing commands. This format is also consistent with `pipenv run` command. Thoughts?

**Comment by venthur** [comment]
Sure, if click can deal with something like
```bash
$ dotenv run ls -lah -f <path-to-dotenv>
```
or
```bash
$ dotenv run git status -f <path-to-dotenv>
```
and is able to associate all options an params to the `run` part. Unfortunately I don't have much experience with click so I have to investigate.

Also, feel free to update this branch according to your suggestion if you like.

**Comment by theskumar** [comment]
This is a valid point and I'll also have to look into it. Thinking out loud, I think the solution around confusing API could be allowing `-f <path-to-env>` before the `run` and everything after `run` can be passed as sub-command as it is.

```
dotenv [-f /path/to/.env] run <executable>
```

**Comment by venthur** [comment]
This should do the trick. It works with:
`dotenv run -f .foo ls -lah` and stuff like `dotenv run -f .foo git log --graph --oneline`

**Comment by venthur** [comment]
Ok I think I'm done. I won't start a fight with coveralls, I believe I've covered all relevant cases. Please review.

**Pull request merged**
