### PR TITLE
Allows `parse_dotenv(stream=StringIO())`

### PR DESCRIPTION
**Pull request by alanjds**
Backwards-compatible API for `parse_dotenv()` that allows a stream having a dotfile to be parsed.

The other option would be to save my already-existing stream in disk and providing the filepath, but this could have security and performance considerations.

### CODE REVIEW

**Comment by theskumar** [comment]
This looks good. `parse_dotenv` is not considered a public api as of yet, but I think it's high time we do so.

Some tests are failing due to installation flake8 issues on travis for python 3.4, that I'll fix up.

Would it be possible for you to add some test cases and related documentation as well, for this so others can followup and use this functionality.

**Comment by alanjds** [comment]
Sure. But not "right now".

Probable after the new year I can get back to work in tests/docs.

Thanks for reviewing it.

**Comment by alanjds** [comment]
Docs and Tests included.

**Comment by theskumar** [comment]
Thanks @alanjds, look great merging this in. Will update changelog in master and make a release. :)

Also i think, i'm going to update 
```
from dotenv.main import parse_dotenv
```
with 
```
from dotenv import parse_dotenv
```

**Pull request merged**
