### PR TITLE
Support override variables

### PR DESCRIPTION
**Pull request by milonimrod**
This is a PR for #5 .
The current open item is that I didn't add the functionality into the ipython support

### CODE REVIEW

**Comment by milonimrod** [comment]
Please notice that on commit 249cbdd80a5e5b2f04d2cacd91d917365f75f5d5 I also added a general case test for the IPython magic (regardless of the override option)

**Comment by theskumar** [comment]
Thanks for pull request. I'll take a look.

**Comment by theskumar** [comment]
This looks super good feature to go in. IPython support with override `-o` argument needs to be documented. Happy to merge and release a new build with updated docs. 👍

**Comment by theskumar** [comment]
I've also resolved a merge conflict with web UI for this branch/PR, but not sure how Github would reflect that on your side. If you face any problem let me know, i'll update the docs on my end.

**Comment by milonimrod** [comment]
No problem. I'll pull the new master, merge them and add the documentation (also, I'll add the support for the verbose on the IPython side)

**Comment by milonimrod** [comment]
@theskumar - all done

**Comment by theskumar** [comment]
I've pushed new release, 0.7.0 is now available with this change 🎉. Thanks :)

**Comment by milonimrod** [comment]
@theskumar you are welcome. Just a small request: in the Readme file you mentioned the pull request with a different username instead of mine.

**Comment by theskumar** [comment]
Readme fixed :)

**Pull request merged**
