### PR TITLE
Added "Converting types"

### PR DESCRIPTION
**Pull request by guettli**

### CODE REVIEW

**Comment by sergeyklay** [comment]
@bbc2 Could you please take a look? Can we have this in the docs?

**Comment by bbc2** [comment]
Thank you for the suggestion but I don't think it's worth having this in the readme because the fact that `os.getenv` returns a string is already documented: https://docs.python.org/3.9/library/os.html#os.getenv. Python-dotenv doesn't change that.

**Comment by ramwin** [comment]
I like this commit. If this was merge into main branch, It really saves newbie a lot of time. And since it only add some suggestions to the README.md file, It didn't break the package's behaviour.

**Comment by alexeyshockov** [comment]
Yeah, such examples would be definitely appreciated. IMO there are no reasons to not mention some existing env vars technics.

**Pull request closed without merging**
