### PR TITLE
Fixed description how to install dotenv with CLI

### PR DESCRIPTION
**Pull request by venthur**
Closes: #106

### CODE REVIEW

**Comment by venthur** [comment]
Which shell are you using, that's causing those problems? This is the first time is see someone recommending to install via: `pip install "package[extra]"` (with quotes around the package name).

**Comment by jaraco** [comment]
I tested a few shells. The quotes aren't required in PowerShell, but are required in xonsh and zsh. Probably best to include them (IMO).

**Comment by theskumar** [comment]
@venthur i'm using zsh shell, also my dotfiles for the same is at: https://github.com/theskumar/dotfiles

**Comment by theskumar** [comment]
I'll go with @jaraco suggestion unless someone has a better suggestion.

**Pull request closed without merging**
