### PR TITLE
Open dotenv_path with UTF-8 encoding

### LINKED ISSUE #74: UnicodeDecodeError occurs when a locale is not set.
UnicodeDecodeError occurs when a locale is not set because the library tries to open .env file in 'US-ASCII' encoding even for non-ASCII files.

### PR DESCRIPTION
**Pull request by earlbread**
This resolves #74.
I think it is better to specify the encoding when opening the .env file.

### CODE REVIEW

**Comment by theskumar** [comment]
It seems like tests are failing, can you look into it.

**Comment by earlbread** [comment]
Ok, I'll look into it and submit again. Thank you!

**Comment by earlbread** [comment]
@theskumar I fixed my code. Thank you!

**Comment by alanjds** [comment]
Is https://github.com/theskumar/python-dotenv/pull/60#issuecomment-357736386 related with this PR?

**Comment by metalcamp** [comment]
Obviously not appropriate place to discuss this, but why this still hasn't been merged?

**Comment by uranusjr** [comment]
We’re hitting this in pypa/pipenv#1963 as well. Either the file should always be decoded with UTF-8, or there should be an additional argument in `fine_dotenv` etc. to allow users to specify a custom encoding.

**Comment by theskumar** [comment]
This will be superseded by #144

**Pull request closed without merging**
