### PR TITLE
Support POSIX parameter expansion

### PR DESCRIPTION
**Pull request by hugochinchilla**
I needed this so much that made a PR without even asking if you would be intereseted on the feature, hope you like it.

Includes proper testing.

### CODE REVIEW

**Comment by theskumar** [comment]
This is something that I had in my already. Thanks for sending the PR. I'll have a look at the implementation in detail and let u know any issues. Expect 1-2 days of time, as I am bit preoccupied with work.

**Comment by hugochinchilla** [comment]
I have reworked the PR, I forgot to test some cases and it wasn't working as expected.

POSIX expansion is working as in most dotenv libraries but it is not truly POSIX compilant.

`${FOO}` and `FOO_${BAR}` will be replaced without problems, but supporting default values in the form of `${FOO:-default_value}` will not.

Truly posix expansion can be achieved using https://github.com/kojiromike/parameter_expansion but I didn't want to include external libraries without asking you first. For me the current behavior is good enough.

**Comment by hugochinchilla** [comment]
just a reminder :)

**Comment by theskumar** [comment]
I am thinking of adding a note about not supporting the default values in POSIX expansion for now. This support can be always be added in new release if we getting any requests for it.

I'm just going over the PR and will let you if I find anything.

**Comment by theskumar** [comment]
Top work on this PR and I'll have to merge this up. Thanks a lot for contribution. 👍 🎉

**Comment by twosigmajab** [comment]
ping @theskumar

**Comment by al-the-x** [comment]
For future readers, per [comment above](https://github.com/theskumar/python-dotenv/pull/30#issuecomment-244036604)

> POSIX expansion is working as in most dotenv libraries but it is not truly POSIX compilant.
> 
> `${FOO}` and `FOO_${BAR}` will be replaced without problems, but supporting default values in the form of `${FOO:-default_value}` will not.

POSIX-compliant expansion of default values inside the `.env` file is not yet implemented, hence [@theskumar's comment](https://github.com/theskumar/python-dotenv/pull/30#issuecomment-245531196)

> I am thinking of adding a note about not supporting the default values in POSIX expansion for now. This support can be always be added in new release if we getting any requests for it.

There doesn't appear to be a mechanism for defining defaults with `python-dotenv` aside from using the idiomatic methods of `dict` like `setdefault` or `get` on the `os.environ` instance or with `os.getenv`.

**Pull request merged**
