### PR TITLE
Added better context for can't find config file error message

### PR DESCRIPTION
**Pull request by snobu**

### CODE REVIEW

**Comment by snobu** [comment]
We should probably add `Code execution continues with system environment variables` since it's not clear if this is recoverable.

**Comment by snobu** [comment]
I fixed all the test... eventually :)

**Comment by snobu** [comment]
Oh, should we add this other thing or not?
`Code execution continues with system environment variable`

**Comment by bbc2** [comment]
I think this looks good.

I wasn't convinced by this change at first because context is provided by the logging module.  When you configure logging in your application, you can choose to show that context.  But I suppose that many users don't know that or don't want to do that, so hard-coding that context could be useful.

I wouldn't add the "Code execution continues with system environment variables" message because it makes it look like using environment variables is unusual, which it isn't (as I explain in https://github.com/theskumar/python-dotenv/issues/164).  I would even go as far as turning that `logger.warning` into `logging.info`, for the same reason, but I would be happy to merge your change as-is.

**Comment by snobu** [comment]
Sorry this took a while and quite a few build cycles as i thought i'm gonna be a smartass and not clone locally but _wing it_ over the browser... which we all know how that ends.

Should be fine now, i amended the logging level to `info`, fixed the tests and dropped the square brackets to be consistent with the rest of the verbose output.

**Comment by bbc2** [comment]
Thanks for the improvements.  I squashed the commits together and slightly simplified the test.

There are other things about the output of python-dotenv that can be improved but this is already a good step forward.

**Comment by theskumar** [comment]
I agree with @bbc2 !

**Comment by Iain-S** [comment]
@bbc2 Would you mind if I changed the logging level back to `WARNING`? When `verbose=True` you would expect something to be printed but, with `INFO`, nothing is printed unless the user has explicitly set the logging level to `INFO`. This is because the default Python logger level is `WARNING`. In other words

```
import dotenv

dotenv.load_dotenv('/not/a/valid/.env/path', verbose=True)
```

does nothing right now.

**Comment by JerPatton** [comment]
> @bbc2 Would you mind if I changed the logging level back to `WARNING`? When `verbose=True` you would expect something to be printed but, with `INFO`, nothing is printed unless the user has explicitly set the logging level to `INFO`. This is because the default Python logger level is `WARNING`. In other words
> 
> ```python
> """myfile.py"""
> import dotenv
> 
> dotenv.load_dotenv('/not/a/valid/.env/path', verbose=True)
> ```
> 
> does nothing right now.

Hi,
Though it is a bit dated now, I see this is still an open issue. 
I quite agree with @Iain-S, would you think that putting back `logging.info` into `logger.warning` would make sense ?

I just had a case where my app crashed because the `.env` file wasn't found and I had no clue it came from this, even after setting the `verbose=True` option.
It would at least provide some debugging info.

**Pull request merged**
