### PR TITLE
Set UTF-8 encoding when reading files in setup.py

### PR DESCRIPTION
**Pull request by altendky**
https://github.com/altendky/pyqt5-tools/issues/38

WIP for:
- [x] testing by @WilburZiWong

### CODE REVIEW

**Comment by altendky** [comment]
@WilburZiWong, could you try installing python-dotenv directly using pip with `install python-dotenv` and confirm you still get the errors reported in https://github.com/altendky/pyqt5-tools/issues/38#issuecomment-576094066?  Assuming that still fails would you then try pip with `install git+https://github.com/altendky/python-dotenv@patch-1` and see if it fixes the issue?

**Comment by altendky** [comment]
Looks like it worked for them https://github.com/altendky/pyqt5-tools/issues/38#issuecomment-576107464.

**Comment by theskumar** [comment]
Thank you so much for the PR! @altendky

**Comment by bbc2** [comment]
Looks goods now  :+1:

**Pull request merged**
