### PR TITLE
add-run-command

### PR DESCRIPTION
**Pull request by sloev**
I think it would be neat if the `dotenv` cli tool had an option to run a given commandline WITH the environment vars sourced from specified file, like a RUNNER.

```
# using the env command to print out env
echo "foo=bar" > .env
$ dotenv -f .env env 
foo=bar
```

### CODE REVIEW

**Comment by sloev** [comment]
any news on merge ... ?

**Comment by theskumar** [comment]
Hi, sorry for keeping you guys waiting, this looks amazing!

I'll have sometime today to look into it and then merge release. 

Thanks @sloev

**Comment by sloev** [comment]
Thanks for the feedback. 
I will look into conforming to expected behaviour tomorrow. 
Yep, set_default is the way to go.

**Comment by sloev** [comment]
all fixed in ac6f522 now using `load_dotenv` and `os.environ` instead.
This means that existing `envs` will be `set_defaulted`with provided `.env` file.

**Comment by theskumar** [comment]
Given a `test.sh` file
```
~/work/theskumar/python-dotenv pr/50
(pytho…/venv)❯ cat test.sh
#!/bin/bash
echo "From .env" $hello
echo "From system" $HOME
```
Uninstalled and re-install the latest code from this PR.
```
~/work/theskumar/python-dotenv pr/50
(pytho…/venv)❯ pip uninstall python-dotenv
Uninstalling python-dotenv-0.6.3:
  /Users/theskumar/work/theskumar/python-dotenv/venv/bin/dotenv
  /Users/theskumar/work/theskumar/python-dotenv/venv/lib/python2.7/site-packages/python-dotenv.egg-link
Proceed (y/n)? y
  Successfully uninstalled python-dotenv-0.6.3
```
```
~/work/theskumar/python-dotenv pr/50
(pytho…/venv)❯ pip install -e .
Obtaining file:///Users/theskumar/work/theskumar/python-dotenv
Requirement already satisfied (use --upgrade to upgrade): click>=5.0 in ./venv/lib/python2.7/site-packages (from python-dotenv==0.6.3)
Installing collected packages: python-dotenv
  Running setup.py develop for python-dotenv
Successfully installed python-dotenv
```
Now the run the `dotenv run` command:
```
~/work/theskumar/python-dotenv
(pytho…/venv)❯ dotenv run test.sh
Traceback (most recent call last):
  File "/Users/theskumar/work/theskumar/python-dotenv/venv/bin/dotenv", line 9, in <module>
    load_entry_point('python-dotenv==0.6.3', 'console_scripts', 'dotenv')()
  File "/Users/theskumar/work/theskumar/python-dotenv/venv/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/theskumar/work/theskumar/python-dotenv/venv/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/theskumar/work/theskumar/python-dotenv/venv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/theskumar/work/theskumar/python-dotenv/venv/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/theskumar/work/theskumar/python-dotenv/venv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/theskumar/work/theskumar/python-dotenv/venv/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/theskumar/work/theskumar/python-dotenv/dotenv/cli.py", line 45, in run
    call(args, env=os.environ)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Do you get the same error, or it's just me?

**Comment by sloev** [comment]
No i didnt get the same error. I will get back to you.

**Comment by sloev** [comment]
I think it is a non populated 'file' arg

**Comment by uranusjr** [comment]
I pulled out this idea and created https://github.com/uranusjr/python-dotenv-run. It uses `os.execlp` to run the command when possible, to avoid creating a subprocess, and the `--override` flag which I find useful.

**Pull request closed without merging**
